### ISSUE TITLE
Editable show only grey box

### ISSUE THREAD

**Issue by khusseini** [dachcom-digital/pimcore-toolbox#106]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

so I got this configuration:
```
toolbox:
    custom_areas:
        hero-title:
            config_elements:
                type:
                    type: select
                    title: 'Type'
                    config:
                        name: type
                        store:
                            standard: 'Standard'
                            mega: 'Mega'
                title:
                    type: input
                    title: 'Title'
                    config: ~
                    col_class: t-col-half
```

and this brick

```
use ToolboxBundle\Document\Areabrick\AbstractAreabrick;
use Pimcore\Model\Document\Tag\Area\Info;

class HeroTitle extends AbstractAreabrick
{
    public function action(Info $info)
    {
        parent::action($info);
    }

    public function getName()
    {
        return 'Hero Title';
    }

    public function getDescription()
    {
        return 'Hero title for pages';
    }

    public function getTemplateLocation()
    {
        return static::TEMPLATE_LOCATION_GLOBAL;
    }

    public function getTemplateSuffix()
    {
        return static::TEMPLATE_SUFFIX_TWIG;
    }
}
```
with this view.html.twig
```
{{ elementConfigBar|raw }}
<div class="my-brick">
    <h3>{{ pimcore_input('title').getData() }}</h3>
</div>
```
and this service configuration

```
AppBundle\Document\Areabrick\HeroTitle:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        calls:
        - [setAreaBrickType, ['external']]
        tags:
        - name: pimcore.area.brick
          id: hero-title
```

When adding the brick to a document, I only get a gray box with "HERO TITLE" written in it. what am I doing wrong here?

here my console output

```
bash-4.4$ bin/console debug:container AppBundle\\Document\\Areabrick\\HeroTitle

Information for Service "AppBundle\Document\Areabrick\HeroTitle"
================================================================

 ---------------- -------------------------------------------------------------------------------------------
  Option           Value                                                                                     
 ---------------- -------------------------------------------------------------------------------------------
  Service ID       AppBundle\Document\Areabrick\HeroTitle
  Class            AppBundle\Document\Areabrick\HeroTitle
  Tags             pimcore.area.brick (id: hero-title)
  Calls            setConfigManager, setBrickConfigBuilder, setLayoutManager, setAreaBrickType, setContainer
  Public           yes
  Synthetic        no
  Lazy             no
  Shared           yes
  Abstract         no
  Autowired        yes
  Autoconfigured   no
 ---------------- -------------------------------------------------------------------------------------------

bash-4.4$ bin/console toolbox:check-config -a hero-title

Area Brick with Id "hero-title" not found.
```

What am I missing here? 

Pimcore version 5.7 and toolbox 2.7
