### ISSUE TITLE
Select has not default value

### ISSUE THREAD

**Issue by khusseini** [dachcom-digital/pimcore-toolbox#107]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I'm using a select to set a type for my custom brick, however when I set the following, I cannot set a default selected value.

```
toolbox:
    custom_areas:
        hero_title:
            config_elements:
                type:
                    type: select
                    title: 'Type'
                    config:
                        name: type
                        store:
                            standard: 'Standard'
                            mega: 'Mega'
                        selected_value: 'standard'
```
