### ISSUE TITLE
Store Provider

### ISSUE THREAD

**Issue by pixel81k** [dachcom-digital/pimcore-toolbox#127]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

to allow dynamic content for p.e. multiselect (not restricted though), allow defining a provider-class instead of store

Example:
```
tags:
                    title: 'Tags'
                    type: multiselect
                    config:
                        store_provider: 'AppBundle\StoreProviders\TagListProvider'
```
