### ISSUE TITLE
[Toolbox2] Areabrick Expansion through AppBundle

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#28]
## Philosophy
- Define custom/project areabricks within toolbox configuration context
- Create elements without using a custom edit.php file –  always render a toolbox config window based on the custom configuration file.

## Preparation

- [x] Find a consistent file structure
- [x] The configuration should look like this:

```yaml
toolbox:
    custom_areas:
        myNewBrick:
            configElements:
                anchorName:
                    type: input
                    config:
                        title: Your Input Title
                anchorTitle:
                    type: input
                    config:
                        title: Another Input Title
```
