### ISSUE TITLE
[Toolbox2] Theme Configuration not working as expected

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-toolbox#34]
According to documentation, this configuration should create two wrappers around my column:

```yml
toolbox:
  theme:
    layout: 'Flex'
    wrapper:
      columns:
        - {tag: 'div', class: 'foundation'}
        - {tag: 'div', class: 'row align-stretch'}
```

But it actually creates 3:

```
array:2 [▼
  "layout" => "Flex"
  "wrapper" => array:3 [▼
    0 => array:2 [▼
      "tag" => "div"
      "class" => "row"
    ]
    1 => array:2 [▼
      "tag" => "div"
      "class" => "foundation"
    ]
    2 => array:2 [▼
      "tag" => "div"
      "class" => "row align-stretch"
    ]
  ]
]
```

Thats because it merges my array with the default bootstrap3 array.
