### ISSUE TITLE
[TB4] Implement SimpleBrick

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#39]
Create Bricks without any custom classes:

```yaml
services:
    app.brick.my_simple_brick:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        tags:
            - {
                name: toolbox.area.simple_brick,
                id: my_simple_brick,
                title: 'Simple Brick (Configurable)',
                description: 'This is a very simple Brick',
                template: 'areas/demo-brick/view.html.twig',
                icon: '/bundles/toolbox/areas/content/icon.svg'
            }
```
