### ISSUE TITLE
mark disallowed_subareas and disallowed_content_snippet_areas as deprecated

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#50]
**Note**: `allowed` node will ignore all disallowed elements - so only elements defined in this node will show up.

New configuration:
```yml
areas_appearance:
        accordion:
            disallowed:
                - image
        content:
            allowed:
                - teaser

snippet_areas_appearance:
        accordion:
            allowed:
                - teaser
                - download
```
