### ISSUE TITLE
Allow Expressions in Appearance Configuration

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-toolbox#77]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes

Having a configuration like this to have only certain bricks for certain "configs" could be easier done using expression engine.

```
toolbox:
    areas_appearance:
        newsletter:
            allowed:
                - newsletter_image
                - newsletter_columns
                - newsletter_text
                - newsletter_blub
       newsletter:
            allowed:
                - b2b_blub
                - b2b_blab
                - b2b_foo
                - b2b_bar
```

like this:

```
toolbox:
    areas_appearance:
        newsletter:
            allowed:
                - @=strpos(areaBrickId, 'newsletter_') == 0
        b2b:
            allowed:
                - @=strpos(areaBrickId, 'b2b_') == 0
```

Allowed values per configuration could actually be calculated within the container building time. If you like that, I could create a PR. This could also affect groups of bricks.
