### ISSUE TITLE
Allow CK-Editor Context-based Configuration

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#82]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

```yml
toolbox:
    context:
        portal1:
            settings:
                merge_with_root: true
            ckeditor:
                global_style_sets:
                    default:
                    -   name: 'Lead For Portal1'
                        element: p
                        attributes:
                            class: 'lead-portal'
    ckeditor:
        global_style_sets:
            default:
            -   name: 'Lead Global'
                element: p
                attributes:
                    class: 'lead'
```
