### ISSUE TITLE
Allow Column Adjuster Context-based Configuration

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-toolbox#83]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Similar to #82 

```yml
toolbox:
    context:
        portal1:
            settings:
                merge_with_root: true
            theme:
                grid:
                    grid_size: 12
                    breakpoints:
                        -
                            identifier: 'xs'
                            name: 'Breakpoint: XS'
                        -
                            identifier: 'sm'
                            name: 'Breakpoint: SM'
                        -
                            identifier: 'md'
                            name: 'Breakpoint: MD'
                        -
                            identifier: 'lg'
                            name: 'Breakpoint: LG'
```
