### ISSUE TITLE
Edit Button in CustomBricks only appears if toolbox conifguration is given twice (with and without underscore)

### ISSUE THREAD

**Issue by ITspirit** [dachcom-digital/pimcore-toolbox#85]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I've installed latest Toolbox and Pimcore Version. Currently i try to create custom Bricks. After a lot of try and error, i figured out a strange behavior. It works, at the moment, but i have the need to define the custom_area in yml File twice!

My Id of the brick is: "custom-newsletter". If i define this alone, the edit Button does not appear. 
If i add a second configuration with "custom_newsletter" (with underscore instead of minus), the edit button appears, with the settings of the first entry (with minus).

It seems, the check if there is an additional custom_area definition does not use the id and check for the class name with underscore as sepearator for the CamelCase  "customNewsletter" => "custom_newsletter"

```
 custom_areas:
        # that's the name of your brick.
        custom-newsletter:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    title: 'Newsletter Action'
                    config:
                        store:
                            action-subscribe: 'Subscribe'
                            action-unsubscribe: 'Unsubscribe'
        custom_newsletter:
            config_elements:
                additional_classes:
                    type: additionalClasses
                    title: 'Dummy-Seems-Like-a-Bug? Is not used just to get the edit button displayed'
```

**Comment by solverat** [comment]
I didn't check it, but i don't think this is a good way to go... You could replace all values (`custom-newsletter`=> `old_newsletter` for example) in your db (`documents_elements`) which would be a better approach.

However, you also need to define your brick as a service:

```yml
services:
    AppBundle\Document\Areabrick\CustomNewsletter\CustomNewsletter:
        parent: ToolboxBundle\Document\Areabrick\AbstractAreabrick
        calls:
            - [setAreaBrickType, ['external']]
        tags:
            - { name: pimcore.area.brick, id: custom_newsletter } # note the id parameter!
```
